### ISSUE TITLE
Disable index generation

### ISSUE THREAD

**Issue by joeldenning** [single-spa/vue-cli-plugin-single-spa#12]
See https://cli.vuejs.org/guide/html-and-static-assets.html#disable-index-generation. Since single-spa applications don't have their own html file, this is desireable.

Also we could maybe delete the index.html file from version control, to avoid confusion about it being able to run as a standalone application.

**Comment by joeldenning** [comment]
@tiagostutz do you have interest in this?

**Comment by tiagostutz** [comment]
Hi there, @joeldenning .! 😃 
First of all, thanks for offering me the issue. 

I’m interested and in this but I still have to run/build the project locally and ger to know better the overall of the structure, which I haven’t done yet, which can take some time. Also, I have to finish that other issue regarding the bundle size in a GitHub Action.

So, if someone more available wants to tackle this issue, that’s fine, but if nobody takes that until I finish the other work, I’ll come back here to take that for sure.

Thanks.!

**Comment by tylerkeesling** [comment]
@joeldenning @tiagostutz I'll take this one.

**Comment by joeldenning** [comment]
Closing as the standalone plugin now uses an HTML file.
