### ISSUE TITLE
vue add single-spa error

### ISSUE THREAD

**Issue by nextdoorUncleLiu** [single-spa/vue-cli-plugin-single-spa#20]
run vue add single-spa
![image](https://user-images.githubusercontent.com/9836853/96428117-fb13ac00-1231-11eb-9524-c9fa983d64e8.png)

**Comment by filoxo** [comment]
This is interesting. [This line](https://github.com/single-spa/vue-cli-plugin-single-spa/blob/master/generator.js#L8) is what is looking for a `vue` property on `dependencies`, so the only way to do that is to either not have a package.json or to not have any dependencies in package.json. Does your application have both a package.json and `dependencies` declared inside of that? As a workaround, you might also try [create-single-spa](https://github.com/single-spa/create-single-spa/) to help generate starter code.
