### ISSUE TITLE
Issue when trying to run 'vue add'

### ISSUE THREAD

**Issue by JoelConstantine** [single-spa/vue-cli-plugin-single-spa#33]
So I initialized a new Vue project directory using `vue create` in the CLI, but when I attempt to run `vue add single-spa` it begins installing only to error out at the Invoking Generator step, throwing `ERROR SyntaxError: Missing catch or finally after try while compiling ejs` and I'm not sure how to address this issue

**Comment by rastislavsvoboda** [comment]
same issue here
examples works with vue 2 and webpack < 5, when I'm trying vue 3 and webpack 5 -> I could not make it run ;(

**Comment by joeldenning** [comment]
This might be related to the recent changes or vuetify/vuex, or they could be related to recent changes in vue cli for vue 3. See https://github.com/single-spa/vue-cli-plugin-single-spa/releases/tag/v3.1.0 and https://github.com/single-spa/vue-cli-plugin-single-spa/releases/tag/v3.1.1

**Comment by Lalaluka** [comment]
I think there is an `<` missing in 
https://github.com/single-spa/vue-cli-plugin-single-spa/blob/914cb25c5c8f5aab06cc7de153672e0eb187a1a9/template/src/main-vue-3.js#L26

This could lead to the compile issues I think. This Line was introduced by #31 
![Bildschirmfoto 2021-09-06 um 14 29 05](https://user-images.githubusercontent.com/26364692/132217664-05eb23a6-040b-4344-8100-d98cf4463e22.png)
ejslint confirms my suspicion and local testing too.

Opened: #34

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/vue-cli-plugin-single-spa/releases/tag/v3.1.2
