### ISSUE TITLE
configuration.output has an unknown property 'jsonpFunction'.

### ISSUE THREAD

**Issue by 695648896** [single-spa/vue-cli-plugin-single-spa#41]
hello,I use vue add single-spa in vue-cli@5.0.0-rc.1
and when i npm run serve:standalone 
some errors like this:
configuration.output has an unknown property 'jsonpFunction'

**Comment by filoxo** [comment]
This will be fixed once Webpack 5 support is added. See also https://github.com/single-spa/vue-cli-plugin-single-spa/pull/40
