### ISSUE TITLE
configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".

### ISSUE THREAD

**Issue by iemektar** [single-spa/vue-cli-plugin-single-spa#43]
Hi,

I created an vue2 application with "npx create-single-spa" and after installation when I just running that command "npm run serve" I'm facing following error.

 INFO  Starting development server...
 ERROR  ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
         - configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".
           BREAKING CHANGE since webpack 5: The devtool option is more strict.
           Please strictly follow the order of the keywords in the pattern.
         - configuration.output has an unknown property 'jsonpFunction'. These properties are valid:
           object { assetModuleFilename?, asyncChunks?, auxiliaryComment?, charset?, chunkFilename?, chunkFormat?, chunkLoadTimeout?, chunkLoading?, chunkLoadingGlobal?, clean?, compareBeforeEmit?, crossOriginLoading?, cssChunkFilename?, cssFilename?, devtoolFallbackModuleFilenameTemplate?, devtoolModuleFilenameTemplate?, devtoolNamespace?, enabledChunkLoadingTypes?, enabledLibraryTypes?, enabledWasmLoadingTypes?, environment?, filename?, globalObject?, hashDigest?, hashDigestLength?, hashFunction?, hashSalt?, hotUpdateChunkFilename?, hotUpdateGlobal?, hotUpdateMainFilename?, iife?, importFunctionName?, importMetaName?, library?, libraryExport?, libraryTarget?, module?, path?, pathinfo?, publicPath?, scriptType?, sourceMapFilename?, sourcePrefix?, strictModuleErrorHandling?, strictModuleExceptionHandling?, trustedTypes?, umdNamedDefine?, uniqueName?, wasmLoading?, webassemblyModuleFilename?, workerChunkLoading?, workerWasmLoading? }
           -> Options affecting the output of the compilation. `output` options tell webpack how to write the compiled files to disk.
           Did you mean output.chunkLoadingGlobal (BREAKING CHANGE since webpack 5)?
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".
   BREAKING CHANGE since webpack 5: The devtool option is more strict.
   Please strictly follow the order of the keywords in the pattern.
 - configuration.output has an unknown property 'jsonpFunction'. These properties are valid:
   object { assetModuleFilename?, asyncChunks?, auxiliaryComment?, charset?, chunkFilename?, chunkFormat?, chunkLoadTimeout?, chunkLoading?, chunkLoadingGlobal?, clean?, compareBeforeEmit?, crossOriginLoading?, cssChunkFilename?, cssFilename?, devtoolFallbackModuleFilenameTemplate?, devtoolModuleFilenameTemplate?, devtoolNamespace?, enabledChunkLoadingTypes?, enabledLibraryTypes?, enabledWasmLoadingTypes?, environment?, filename?, globalObject?, hashDigest?, hashDigestLength?, hashFunction?, hashSalt?, hotUpdateChunkFilename?, hotUpdateGlobal?, hotUpdateMainFilename?, iife?, importFunctionName?, importMetaName?, library?, libraryExport?, libraryTarget?, module?, path?, pathinfo?, publicPath?, scriptType?, sourceMapFilename?, sourcePrefix?, strictModuleErrorHandling?, strictModuleExceptionHandling?, trustedTypes?, umdNamedDefine?, uniqueName?, wasmLoading?, webassemblyModuleFilename?, workerChunkLoading?, workerWasmLoading? }
   -> Options affecting the output of the compilation. `output` options tell webpack how to write the compiled files to disk.
   Did you mean output.chunkLoadingGlobal (BREAKING CHANGE since webpack 5)?
    at validate (C:\Users\iemektar\Desktop\test\home\node_modules\webpack\node_modules\schema-utils\dist\validate.js:105:11)
    at validateSchema (C:\Users\iemektar\Desktop\test\home\node_modules\webpack\lib\validateSchema.js:78:2)
    at create (C:\Users\iemektar\Desktop\test\home\node_modules\webpack\lib\webpack.js:111:24)
    at webpack (C:\Users\iemektar\Desktop\test\home\node_modules\webpack\lib\webpack.js:158:32)
    at f (C:\Users\iemektar\Desktop\test\home\node_modules\webpack\lib\index.js:63:16)
    at serve (C:\Users\iemektar\Desktop\test\home\node_modules\@vue\cli-service\lib\commands\serve.js:174:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by filoxo** [comment]
This will be resolved when #40 is merged.

**Comment by filoxo** [comment]
[vue-cli-plugin-single-spa@3.2.0](https://github.com/single-spa/vue-cli-plugin-single-spa/releases/tag/v3.2.0) has been released. I'm going to close this but if you continue to experience issues, please feel free to reopen.

**Comment by filoxo** [comment]
@iemektar thanks for the follow up! this error should be resolved in #44.

**Comment by rodnneysantiago** [comment]
Any news on when these changes will be available?

**Comment by iemektar** [comment]
Still I'm getting same error, nothing changed.

**Comment by filoxo** [comment]
This fix has been published in [vue-cli-plugin-single-spa@3.3.0](https://github.com/single-spa/vue-cli-plugin-single-spa/releases/tag/v3.3.0).
