### ISSUE TITLE
create single-spa with VUE3 and VUE2(Default) ERROR on run server

### ISSUE THREAD

**Issue by wallereducbank** [single-spa/vue-cli-plugin-single-spa#45]
I created a micro frontend with Vue3(default) and when i run yarn serve i'm getting this error:

![image](https://user-images.githubusercontent.com/98391614/157680393-d4974cf9-0323-44aa-90d9-9a26475a7904.png)

**Comment by filoxo** [comment]
This will be resolved in https://github.com/single-spa/vue-cli-plugin-single-spa/pull/44

**Comment by filoxo** [comment]
This fix has been published in [vue-cli-plugin-single-spa@3.3.0](https://github.com/single-spa/vue-cli-plugin-single-spa/releases/tag/v3.3.0).
