### ISSUE TITLE
How to setup SSR?

### ISSUE THREAD

**Issue by svihpinc** [single-spa/vue-cli-plugin-single-spa#48]
In the react example here: https://github.com/isomorphic-microfrontends/navbar/blob/master/webpack.config.js, webpack is used to build a nodejs targeted file `server.mjs` which is imported by the server when a request is recieved

How to do this with vue-cli project?

**Comment by filoxo** [comment]
Closing as a duplicate. Let's track this in the single-spa-vue repo.
